# Generated by Django 5.1.1 on 2024-10-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishtype",
            name="name",
            field=models.CharField(max_length=63),
        ),
    ]
