# Generated by Django 5.1.2 on 2024-10-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={"ordering": ["username"]},
        ),
    ]
