# Generated by Django 5.1.1 on 2024-10-05 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_cook_options_alter_dish_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="cooks",
            field=models.ManyToManyField(
                blank=True, related_name="dishes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
